### PR TITLE
Individual test links not resolving

### PR DESCRIPTION
**Pull request by cagiti**
The featureFileName contains the '.feature' type, the '.' needs to be substituted with a hyphen ('-') within the hyperlink to resolve correctly.

### CODE REVIEW

**Comment by jay-w-jensen** [comment]
I think that the '/' needs to be replaced with a '-' as well; my links go to features/blah.feature.html but my reports are at features-blah-feature.html.

**Comment by timsheng** [comment]
when this PR will be merged to master? now it has conflict with cucumber-jvm plugins.

**Comment by garethjevans** [comment]
This has been fixed as part of another review - @timsheng what are the conflicts with cucumber-jvm plugins?

**Comment by timsheng** [comment]
@garethjevans  when using this plugin and cucumber-jvm together, the feature link in the notification sent to slack will be directed to a wrong url.
e.g: cucumber-html-reports/features/login_s-feature.html
actually cucumber-html-reports/features-login_s-feature.html is right.
i just changed the `getFeatureUri()` in FeatureResult.java file
`	public String getFeatureUri() {
		return this.name.replaceAll("/", "-").replace(".feature", "-feature") + ".html";
	}`
then it works fine.

**Pull request closed without merging**
